# Generated by Django 5.1.1 on 2024-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charmap',
            name='character_chinese',
        ),
        migrations.RemoveField(
            model_name='charmap',
            name='character_english',
        ),
        migrations.RemoveField(
            model_name='charmap',
            name='character_id',
        ),
        migrations.AddField(
            model_name='charmap',
            name='c_id',
            field=models.IntegerField(default=-999),
        ),
        migrations.AddField(
            model_name='charmap',
            name='chinese',
            field=models.CharField(default='_', max_length=1),
        ),
        migrations.AddField(
            model_name='charmap',
            name='english',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
